package workflow

import "time"

type Event struct {
	// ID is a unique ID for the event generated by the event streamer.
	ID int64
	// CreatedAt is the time that the event was produced and is generated by the event streamer.
	CreatedAt time.Time

	// Record is the associated wire record.
	Record *WireRecord
}
